dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:keithw/glfw3'
          packages:
            - g++-5
            - g++-5-multilib
            - libglfw3
            - libxrandr-dev
            - libxcursor-dev
            - libxi-dev
            - libxinerama-dev
            - libglfw3-dev
      env: COMPILER=g++-5

before_script:
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd $PARENTDIR/build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER $PARENTDIR
  - make

notifications:
  email:
    on_success: never
    on_failure: always
